# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              卞懂の个人博客
logo:               # Logo image URL
cover_image:        '/images/general/QooBee-Wave-Wallpaper.png'
description:        "<h2>卞(biàn)懂的博客</h2><p>佛说：不要只盯着这个季节，错过了今冬，明年才懂得珍惜。<br>- <a href='https://en.wikipedia.org/wiki/Dr._Bian'>Dr. Bian</a></p>"
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://bcdon.github.io' # The base hostname & protocol for your site
twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/aspirethemes/
instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  6
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Biandong
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: https://s.gravatar.com/avatar/15589c24c2b489f42059555a07f553af?s=80
    email:    741702321@qq.com
    website:  https://www.bcdon.com
    github:   https://github.com/bcdon
    twitter:  https://twitter.com/

valine_comment:
  enable: true
# app_id
  leancloud_appid: 7WLbcATfsdUEteJsgIxasDxO-gzGzoHsz
# app_key
  leancloud_appkey: NsIt6kuXXNgAu3z7PhoABCPW
# placeholde
  placeholder: “Just go go"