# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              卞懂の个人博客
logo:               # Logo image URL
cover_image:        '/images/general/herowall.jpg'
typedtext:          '我问佛：世间为何有那么多遗憾？", "佛曰：这是一个婆娑世界，婆娑即遗憾。","佛曰：没有遗憾，给你再多幸福也不会体会快乐。","我问佛：如果遇到了可以爱的人，却又怕不能把握该怎么办？","佛曰：留人间多少爱，迎浮世千重变。","佛曰：和有情人，做快乐事 别问是劫是缘。","佛曰：人生有八苦：生，老，病，死，爱别离，怨长久，求不得，放不下。","佛曰：命由己造，相由心生，世间万物皆是化相，心不动，万物皆不动，心不变，万物皆不变。","佛说：万法皆生，皆系缘份，偶然的相遇，暮然的回首，注定彼此的一生，只为眼光交汇的刹那。","佛说：缘起即灭，缘生已空。'
herotitle:          "<h2>卞(biàn)懂的自留地 (・へ・)</h2>"
description:        "- <a href='https://www.bcdon.com'>Mr. biàn</a>"
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://bcdon.github.io' # The base hostname & protocol for your site
twitter:            https://twitter.com/aspirethemes
facebook:           https://www.facebook.com/aspirethemes/
instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  6
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Biandong:
    name:     Biandǒng
    bio:      1998年来到这个传奇的星球，没有跌宕起伏的传奇人生，更不是史诗般的英雄人物；混迹于IT界四年又余，无大才，唯有大志，日月可鉴。
    gravatar: /images/general/touxiang.gif
    email:    741702321@qq.com
    website:  https://www.bcdon.com
    github:   https://github.com/bcdon
    twitter:  https://twitter.com/

# 评论
valine_comment:
  enable: true
  # app_id
  leancloud_appid: 7WLbcATfsdUEteJsgIxasDxO-gzGzoHsz
  # app_key
  leancloud_appkey: NsIt6kuXXNgAu3z7PhoABCPW
  # placeholde
  placeholder: “Just go go"